<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search by Applicant (Company)_applicant</name>
   <tag></tag>
   <elementGuidId>dd873c38-ee51-4785-906d-38b34c027dd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#applicant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='applicant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter at least 2 characters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea017311-0f47-4fda-a87d-6b0e8fb81e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>applicant</value>
      <webElementGuid>3f75c871-38ba-4d78-9386-2413d691ee53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>zb</value>
      <webElementGuid>65a1974b-be1d-49bc-8098-6bad5fc343d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>94a19408-4b0c-4f9f-908b-25949ade33a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>cc4ea345-93d8-4b98-81d7-280dba53ba87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter at least 2 characters</value>
      <webElementGuid>57f1bb1f-1a8c-40d2-ab94-fd2f2381e7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>applicant</value>
      <webElementGuid>50beede4-f3f0-4722-8a7c-5fd5286d7d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applicant&quot;)</value>
      <webElementGuid>afb7c554-9e38-47ac-a7d0-5b1b73adaa44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='applicant']</value>
      <webElementGuid>287700cf-3150-4ad0-94f6-be35b2d5e4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form2']/input</value>
      <webElementGuid>5c328996-3a4b-4ca5-ab89-1b6b27bb8288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/input</value>
      <webElementGuid>c22c6672-02b5-47b0-ac3e-fd6cada4f61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'applicant' and @placeholder = 'Enter at least 2 characters' and @id = 'applicant']</value>
      <webElementGuid>b7a48398-e7c5-4234-94ab-4a853d7230e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
